language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.5"
sudo: required

services:
  - postgresql

before_install:
  - psql -c 'create database hexandriaTest' -U postgres

install:
  - mvn clean install