language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.5"
sudo: required

services:
  - postgresql

before_script:
  - psql -c "create user admin with superuser password '123456789';" -U postgres
  - psql -c 'create database hexandriatest' -U postgres
  - psql -c "grant all on database hexandriatest to admin;" -U postgres

