DROP ALL OBJECTS;
CREATE SCHEMA IF NOT EXISTS hexandria;
DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY ,
  login VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  email VARCHAR(255)
);