DROP ALL OBJECTS;
CREATE SCHEMA IF NOT EXISTS hexandria;
DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY ,
  login TEXT UNIQUE ,
  password TEXT,
  email TEXT
);