CREATE EXTENSION IF NOT EXISTS CITEXT;
CREATE SCHEMA IF NOT EXISTS hexandria;
CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  login CITEXT UNIQUE,
  password TEXT,
  email TEXT
);
CREATE UNIQUE INDEX ON users (id);